#if UNITY_EDITOR

using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace GameDevKit.CodeGenerator
{
    public class ClassGenerator
    {
        private int _indent;
        private int _tabToSpace = 4;
        private bool _allowTab = false;
        private StringBuilder _builder = new();

        public void CreateFile(string filePath)
        {
            _builder.Insert(0, $"// Auto-generated by {typeof(ClassGenerator)}\n\n");

            if (!_allowTab)
            {
                ConvertTabToSpace();
            }

            Directory.CreateDirectory(Path.GetDirectoryName(filePath));

            File.WriteAllText(filePath, _builder.ToString());
            AssetDatabase.Refresh();
        }

        public void AddLine(string line = "")
        {
            if (line.IsNullOrEmpty())
            {
                _builder.Append('\n');
                return;
            }

            if (line.Contains("}")) _indent--;

            var tabCount = 0;

            foreach (var c in line)
            {
                if (c == '\t')
                {
                    tabCount++;
                    continue;
                }

                break;
            }

            for (var i = 0; i < _indent - tabCount; i++)
            {
                _builder.Append("\t");
            }

            _builder.Append($"{line}\n");

            if (line.Contains("{")) _indent++;
        }

        public void ConfigTab(bool allowTab, int tabToSpace)
        {
            _allowTab = allowTab;
            _tabToSpace = tabToSpace;
        }

        private void ConvertTabToSpace()
        {
            _builder.Replace("\t", new string(' ', _tabToSpace));
        }
    }
}

#endif